// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"be/config"
	"be/internal/infrastructure/blockchain/ether"
	"be/internal/infrastructure/cache/redis"
	"be/internal/infrastructure/database/postgres"
	"be/internal/infrastructure/database/repository"
	"be/internal/service"
	"be/internal/transport/http/handler"
	"be/internal/transport/http/middleware"
	"be/internal/transport/http/router"
	"be/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication() (App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return App{}, err
	}
	zapLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return App{}, err
	}
	redisCache, err := redis.NewCache(configConfig, zapLogger)
	if err != nil {
		return App{}, err
	}
	postgresDB, err := postgres.NewDB(configConfig, zapLogger)
	if err != nil {
		return App{}, err
	}
	iUserRepository := repository.NewUserRepository(postgresDB, zapLogger)
	iAuthJWTService := service.NewAuthJWTService(configConfig, zapLogger, redisCache, iUserRepository)
	authJWTHandler := handler.NewAuthJWTHandler(iAuthJWTService, zapLogger)
	iIdentityRepository := repository.NewIdentityRepository(postgresDB)
	imtRepository := repository.NewMerkletreeRepository(configConfig, postgresDB)
	iAuthZkService, err := service.NewAuthZkService(configConfig, zapLogger, redisCache, iIdentityRepository, imtRepository)
	if err != nil {
		return App{}, err
	}
	authZkHandler := handler.NewAuthZkHandler(zapLogger, iAuthZkService)
	iCitizenIdentityRepository := repository.NewCitizenIdentityRepository(postgresDB, zapLogger)
	iAcademicDegreeRepository := repository.NewAcademicDegreeRepository(postgresDB, zapLogger)
	iHealthInsuranceRepository := repository.NewHealthInsuranceRepository(postgresDB, zapLogger)
	iDriverLicenseRepository := repository.NewDriverLicenseRepository(postgresDB, zapLogger)
	iPassportRepository := repository.NewPassportRepository(postgresDB, zapLogger)
	iDocumentService := service.NewDocumentService(configConfig, iCitizenIdentityRepository, iAcademicDegreeRepository, iHealthInsuranceRepository, iDriverLicenseRepository, iPassportRepository)
	documentHandler := handler.NewDocumentHandler(iDocumentService)
	routerRouter := router.NewRouter(authJWTHandler, authZkHandler, documentHandler)
	middlewareMiddleware := middleware.NewMiddleware(configConfig, zapLogger)
	server := NewServer(configConfig, zapLogger)
	app := App{
		Config:     configConfig,
		Router:     routerRouter,
		Middleware: middlewareMiddleware,
		Server:     server,
		Log:        zapLogger,
		Postgres:   postgresDB,
		Redis:      redisCache,
	}
	return app, nil
}

// wire.go:

// Log Set
var logSet = wire.NewSet(logger.NewLogger)

// Config Set
var configSet = wire.NewSet(config.NewConfig)

// Infra Set
var dbSet = wire.NewSet(postgres.NewDB)

var migrateSet = wire.NewSet()

var cacheSet = wire.NewSet(redis.NewCache)

// var queueSet = wire.NewSet(rabbitmq.NewQueue, rabbitmq.NewConsumer, rabbitmq.NewProducer)
var etherSet = wire.NewSet(ether.NewEther)

// Handler Set
var handlerSet = wire.NewSet(handler.NewAuthJWTHandler, handler.NewAuthZkHandler, handler.NewDocumentHandler)

// Service Set
var serviceSet = wire.NewSet(service.NewAuthJWTService, service.NewAuthZkService, service.NewCredentialService, service.NewDocumentService, service.NewProofService, service.NewSchemaService)

// Repository Set
var repositorySet = wire.NewSet(repository.NewAcademicDegreeRepository, repository.NewBlockchainRepository, repository.NewCitizenIdentityRepository, repository.NewCredentialRepository, repository.NewDriverLicenseRepository, repository.NewHealthInsuranceRepository, repository.NewIdentityRepository, repository.NewMerkletreeRepository, repository.NewPassportRepository, repository.NewProofRepository, repository.NewSchemaRepository, repository.NewStateTransitionRepository, repository.NewUserRepository)

// Router Set
var routerSet = wire.NewSet(router.NewRouter)

// Middleware Set
var middlewareSet = wire.NewSet(middleware.NewMiddleware)

// Server Set
var serverSet = wire.NewSet(NewServer)
