// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"be/config"
	"be/internal/infrastructure/blockchain/ether"
	"be/internal/infrastructure/cache/redis"
	"be/internal/infrastructure/database/postgres"
	"be/internal/infrastructure/database/repository"
	"be/internal/infrastructure/ipfs"
	"be/internal/service"
	"be/internal/transport/http/handler"
	"be/internal/transport/http/middleware"
	"be/internal/transport/http/router"
	"be/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApplication() (App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return App{}, err
	}
	zapLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return App{}, err
	}
	postgresDB, err := postgres.NewDB(configConfig, zapLogger)
	if err != nil {
		return App{}, err
	}
	redisCache, err := redis.NewCache(configConfig, zapLogger)
	if err != nil {
		return App{}, err
	}
	iUserRepository := repository.NewUserRepository(postgresDB, zapLogger)
	iAuthJWTService := service.NewAuthJWTService(configConfig, zapLogger, redisCache, iUserRepository)
	authJWTHandler := handler.NewAuthJWTHandler(iAuthJWTService, zapLogger)
	iIdentityRepository := repository.NewIdentityRepository(postgresDB)
	imtRepository := repository.NewMerkletreeRepository(configConfig, postgresDB)
	iIdentityService := service.NewIdentityService(configConfig, iIdentityRepository, imtRepository)
	iVerifierService, err := service.NewVerifierService(configConfig)
	if err != nil {
		return App{}, err
	}
	iAuthZkService, err := service.NewAuthZkService(configConfig, zapLogger, redisCache, iIdentityService, iVerifierService)
	if err != nil {
		return App{}, err
	}
	authZkHandler := handler.NewAuthZkHandler(configConfig, zapLogger, iAuthZkService)
	iCitizenIdentityRepository := repository.NewCitizenIdentityRepository(postgresDB, zapLogger)
	iAcademicDegreeRepository := repository.NewAcademicDegreeRepository(postgresDB, zapLogger)
	iHealthInsuranceRepository := repository.NewHealthInsuranceRepository(postgresDB, zapLogger)
	iDriverLicenseRepository := repository.NewDriverLicenseRepository(postgresDB, zapLogger)
	iPassportRepository := repository.NewPassportRepository(postgresDB, zapLogger)
	iDocumentService := service.NewDocumentService(configConfig, iCitizenIdentityRepository, iAcademicDegreeRepository, iHealthInsuranceRepository, iDriverLicenseRepository, iPassportRepository)
	documentHandler := handler.NewDocumentHandler(iDocumentService)
	iCredentialRequestRepository := repository.NewCredentialRequestRepository(postgresDB)
	iVerifiableCredentialRepository := repository.NewVerifiableCredentialRepository(postgresDB, configConfig)
	iSchemaRepository := repository.NewSchemaRepository(postgresDB)
	iCredentialService := service.NewCredentialService(configConfig, iIdentityService, iDocumentService, iCredentialRequestRepository, iVerifiableCredentialRepository, iSchemaRepository)
	credentialHandler := handler.NewCredentialHandler(iCredentialService)
	pinata := ipfs.NewPinata(configConfig)
	iSchemaAttributeRepository := repository.NewSchemaAttributeRepository(configConfig, postgresDB)
	iSchemaService := service.NewSchemaService(configConfig, pinata, iIdentityRepository, iSchemaRepository, iSchemaAttributeRepository)
	schemaHandler := handler.NewSchemaHandler(iSchemaService)
	iProofRepository := repository.NewProofRepository(postgresDB)
	iProofService := service.NewProofService(configConfig, zapLogger, iVerifierService, iIdentityService, iSchemaRepository, iProofRepository)
	proofHandler := handler.NewProofHandler(iProofService)
	iCircuitService := service.NewCircuitService(configConfig, zapLogger, iProofRepository, iVerifiableCredentialRepository, iIdentityService)
	circuitHandler := handler.NewCircuitHandler(iCircuitService, configConfig, zapLogger)
	iStatisticRepository := repository.NewStatisticRepository(postgresDB, configConfig)
	iStatisticService := service.NewStatisticService(configConfig, iStatisticRepository)
	statisticHandler := handler.NewStatisticHandler(iStatisticService)
	routerRouter := router.NewRouter(postgresDB, authJWTHandler, authZkHandler, documentHandler, credentialHandler, schemaHandler, proofHandler, circuitHandler, statisticHandler, iAuthZkService)
	middlewareMiddleware := middleware.NewMiddleware(configConfig, zapLogger)
	server := NewServer(configConfig, zapLogger)
	app := App{
		Config:     configConfig,
		Router:     routerRouter,
		Middleware: middlewareMiddleware,
		Server:     server,
		Log:        zapLogger,
		Postgres:   postgresDB,
		Redis:      redisCache,
	}
	return app, nil
}

// wire.go:

// Log Set
var logSet = wire.NewSet(logger.NewLogger)

// Config Set
var configSet = wire.NewSet(config.NewConfig)

// Infra Set
var dbSet = wire.NewSet(postgres.NewDB)

var migrateSet = wire.NewSet()

var cacheSet = wire.NewSet(redis.NewCache)

var ipfsSet = wire.NewSet(ipfs.NewPinata)

// var queueSet = wire.NewSet(rabbitmq.NewQueue, rabbitmq.NewConsumer, rabbitmq.NewProducer)
var etherSet = wire.NewSet(ether.NewEther)

// Handler Set
var handlerSet = wire.NewSet(handler.NewAuthJWTHandler, handler.NewAuthZkHandler, handler.NewDocumentHandler, handler.NewSchemaHandler, handler.NewCredentialHandler, handler.NewProofHandler, handler.NewCircuitHandler, handler.NewStatisticHandler)

// Service Set
var serviceSet = wire.NewSet(service.NewAuthJWTService, service.NewAuthZkService, service.NewCredentialService, service.NewDocumentService, service.NewProofService, service.NewSchemaService, service.NewIdentityService, service.NewVerifierService, service.NewCircuitService, service.NewStatisticService)

// Repository Set
var repositorySet = wire.NewSet(repository.NewAcademicDegreeRepository, repository.NewCitizenIdentityRepository, repository.NewCredentialRequestRepository, repository.NewDriverLicenseRepository, repository.NewHealthInsuranceRepository, repository.NewIdentityRepository, repository.NewMerkletreeRepository, repository.NewPassportRepository, repository.NewProofRepository, repository.NewSchemaAttributeRepository, repository.NewSchemaRepository, repository.NewStateTransitionRepository, repository.NewUserRepository, repository.NewVerifiableCredentialRepository, repository.NewStatisticRepository)

// Router Set
var routerSet = wire.NewSet(router.NewRouter)

// Middleware Set
var middlewareSet = wire.NewSet(middleware.NewMiddleware)

// Server Set
var serverSet = wire.NewSet(NewServer)
